#!/bin/bash

GITREPO=https://github.com/PCSX2/pcsx2.git
REPODIR=pcsx2
BUILD=release   # devel | debug | prof | release


cd $HOME
if [ ! -d ${HOME}/${REPODIR}/.git ]; then
    git clone $GITREPO
fi

cd ${HOME}/${REPODIR}
git pull
./build.sh --egl --${BUILD} --strip --extra --lto --no-cross-multilib
